import streamlit as st
from util.utility import check_password


# Do not continue if check_password is not True.  
if not check_password():  
    st.stop()

st.title("About Us")

st.subheader("Problem Statement")
with st.container(border=True):
    st.write("""Archaeological finds found in Singapore waters and land are documented in archaeological site reports made available\
            on sources like NUS E-Press (https://epress.nus.edu.sg/sitereports/). However, the site reports are typically in an\
            unstructured text format. The format may also vary across different authors or organisations researching on the archaeological\
            site. This makes it challenging to build up a list of vocabularies (or categories) commonly used to describe the\
            archaeological finds.""")

st.subheader("Proposed Solution")
with st.container(border=True):
    st.write("""With the use of LLM, it is expected to cut down the manual effort required to look through the site reports\
            and rationalise the list of categories used to describe the archaeological finds. The new process will involve\
            users to focus on newly suggested categories and their corresponding rationale for suggesting the categories\
            as generated by LLM.""")

st.subheader("Impact")
with st.container(border=True):
    st.write("""By creating a list of vocabularies to describe the archaeological finds, this information can be used to increase\
            searchability and allow better retrieval of archaeology related content and resources.""")
        
st.subheader("Data Sources")
with st.container(border=True):
    st.markdown("""
    Data on archaeological finds are extracted from NUS E-Press (https://epress.nus.edu.sg/sitereports/). Supplementary data on\
    the vocabularies used to describe decoration techniques are extracted from various sources:
    - Getty Art & Architecture Thesaurus (https://www.getty.edu/research/tools/vocabularies/aat/)
    - Southeast Asian Ceramic Society Glossary (https://www.seaceramic.org.sg/resources/glossary/)
    - Metropolitan Museum of Art Publication on A Handbook of Chinese Ceramics (https://resources.metmuseum.org/resources/metpublications/pdf/A_Handbook_of_Chinese_Ceramics.pdf)
    """)

st.subheader("Application Features")
with st.container(border=True):
    st.write("There are two main features in this application. Click below to find out more:")
    st.page_link("Archaeology_Categoriser_Assistant.py", label="- Categoriser Assistant", icon="🚀")
    st.page_link("pages/1_Query_Sites.py", label="- Query Site Reports", icon="🚀")
